### ISSUE TITLE
cannot change btn's colors

### ISSUE THREAD

**Issue by dmatsanganis** [Shashank02051997/FancyAlertDialog-Android#16]
i have follow the steps as the read.me guide it, but i cannot change the color of the two buttons. Neither the                 .setNegativeBtnBackgroundRes not the .setNegativeBtnBackground seems to work properly (same for the positive button). Is anything i can do to change the default color or did I have to do anything more in order to change the btn's color?

**Comment by Shashank02051997** [comment]
@dimitrismatsanganis 
Pass your color that's it

.setPositiveBtnBackgroundRes(R.color.positiveButton) // Pass the color from color.xml
.setNegativeBtnBackgroundRes(R.color.negativeButton) // Pass the color from color.xml

If this will not resolve the issue then lets connect on any social site medium where I can help you with it
